#include<iostream.h>
#include<conio.h>
int main()
{
clrscr();
int mn;
cout<<"enter the month number:";
cin>>mn;
if(mn==1)
{
cout<<"JANUARY";
}
else if (mn==2)
{
cout<<"FEBRUARY";
}
else if (mn==3)
{
cout<<"MARCH";
}
else if (mn==4)
{
cout<<"APRIL";
}
else if (mn==5)
{
cout<<"MAY";
}
else if (mn==6)
{
cout<<"JUNE";
}
else if (mn==7)
{
cout<<"JULY";
}
else if (mn==8)
{
cout<<"AUGUST";
}
else if (mn==9)
{
cout<<"SEPTEMBER";
}
else if (mn==10)
{
cout<<"OCTOBER";
}
else if (mn==11)
{
cout<<"NOVEMBER";
}
else if (mn==12)
{
cout<<"DECEMBER";
}
else
{
cout<<"INVALID NUMBER";
}
getch();
return 0;
}